import type { ReportFilterType } from '../../data/reportsWorkspace'

export type ReportLocale = 'ar' | 'en'

export const reportLabels = {
  ar: {
    apply: 'تطبيق التقرير',
    refresh: 'تحديث التقرير',
    clear: 'مسح الفلاتر',
    print: 'طباعة',
    pdf: 'تصدير PDF',
    excel: 'تصدير Excel',
    back: 'رجوع',
    settings: 'إعدادات التقرير',
    summary: 'ملخص التقرير',
    result: 'نتائج التقرير',
    generatedAt: 'وقت الإنشاء',
    period: 'الفترة',
    selectPlaceholder: 'اختر...',
    emptyTitle: 'جاهز لتشغيل التقرير',
    emptyBody: 'حدد الفترة وخيارات التقرير ثم اضغط تطبيق التقرير لعرض النتائج.',
    filter: {
      dateRange: 'الفترة',
      fromDate: 'من تاريخ',
      toDate: 'إلى تاريخ',
      account: 'الحساب',
      customer: 'العميل',
      supplier: 'المورد',
      currency: 'العملة',
      branch: 'الفرع',
      costCenter: 'مركز التكلفة',
      status: 'الحالة',
      taxPeriod: 'الفترة الضريبية',
      bankAccount: 'حساب البنك/الصندوق',
      assetType: 'نوع الأصل',
      item: 'الصنف/المنتج',
      comparisonPeriod: 'فترة المقارنة',
      groupBy: 'تجميع حسب',
    },
    metrics: {
      totalAssets: 'إجمالي الأصول',
      totalLiabilities: 'إجمالي الخصوم',
      netProfit: 'صافي الربح',
      variance: 'فرق المقارنة',
      openingBalance: 'الرصيد الافتتاحي',
      totalDebit: 'إجمالي المدين',
      totalCredit: 'إجمالي الدائن',
      closingBalance: 'الرصيد الختامي',
      totalAmount: 'إجمالي المبلغ',
      currentBucket: 'غير متأخر',
      overdueBucket: 'متأخر',
      riskCount: 'حالات مخاطرة',
      actual: 'الفعلي',
      planned: 'المخطط',
      varianceAmount: 'مبلغ الانحراف',
      variancePercent: 'نسبة الانحراف',
      cashIn: 'النقد الداخل',
      cashOut: 'النقد الخارج',
      netMovement: 'صافي الحركة',
      unmatched: 'غير مطابق',
      acquisitionCost: 'تكلفة الاقتناء',
      accumulatedDepreciation: 'إهلاك متراكم',
      bookValue: 'القيمة الدفترية',
      assetCount: 'عدد الأصول',
      inputTax: 'ضريبة المدخلات',
      outputTax: 'ضريبة المخرجات',
      taxDue: 'صافي الضريبة',
      complianceAlerts: 'تنبيهات امتثال',
      revenue: 'الإيراد',
      cost: 'التكلفة',
      grossMargin: 'الهامش الإجمالي',
      marginPercent: 'نسبة الهامش',
      kpiCount: 'عدد المؤشرات',
      trend: 'الاتجاه',
      alerts: 'التنبيهات',
      scheduledExports: 'تصديرات مجدولة',
    },
  },
  en: {
    apply: 'Apply Report',
    refresh: 'Refresh Report',
    clear: 'Clear Filters',
    print: 'Print',
    pdf: 'Export PDF',
    excel: 'Export Excel',
    back: 'Back',
    settings: 'Report Settings',
    summary: 'Report Summary',
    result: 'Report Results',
    generatedAt: 'Generated at',
    period: 'Period',
    selectPlaceholder: 'Select...',
    emptyTitle: 'Ready to run report',
    emptyBody: 'Select the period and report options, then apply the report to show results.',
    filter: {
      dateRange: 'Period',
      fromDate: 'From date',
      toDate: 'To date',
      account: 'Account',
      customer: 'Customer',
      supplier: 'Supplier',
      currency: 'Currency',
      branch: 'Branch',
      costCenter: 'Cost center',
      status: 'Status',
      taxPeriod: 'Tax period',
      bankAccount: 'Bank/cashbox account',
      assetType: 'Asset type',
      item: 'Item/product',
      comparisonPeriod: 'Comparison period',
      groupBy: 'Group by',
    },
    metrics: {
      totalAssets: 'Total assets',
      totalLiabilities: 'Total liabilities',
      netProfit: 'Net profit',
      variance: 'Variance',
      openingBalance: 'Opening balance',
      totalDebit: 'Total debit',
      totalCredit: 'Total credit',
      closingBalance: 'Closing balance',
      totalAmount: 'Total amount',
      currentBucket: 'Current',
      overdueBucket: 'Overdue',
      riskCount: 'Risk cases',
      actual: 'Actual',
      planned: 'Planned',
      varianceAmount: 'Variance amount',
      variancePercent: 'Variance %',
      cashIn: 'Cash in',
      cashOut: 'Cash out',
      netMovement: 'Net movement',
      unmatched: 'Unmatched',
      acquisitionCost: 'Acquisition cost',
      accumulatedDepreciation: 'Accum. depreciation',
      bookValue: 'Book value',
      assetCount: 'Assets',
      inputTax: 'Input tax',
      outputTax: 'Output tax',
      taxDue: 'Tax due',
      complianceAlerts: 'Compliance alerts',
      revenue: 'Revenue',
      cost: 'Cost',
      grossMargin: 'Gross margin',
      marginPercent: 'Margin %',
      kpiCount: 'KPI count',
      trend: 'Trend',
      alerts: 'Alerts',
      scheduledExports: 'Scheduled exports',
    },
  },
} as const

export function filterLabel(locale: ReportLocale, filter: ReportFilterType) {
  return reportLabels[locale].filter[filter]
}

export function metricLabel(locale: ReportLocale, metric: string) {
  return reportLabels[locale].metrics[metric as keyof typeof reportLabels.ar.metrics] ?? metric
}
