import { buildAccountFinancialSummary, sumAccountInvoiceRows } from './aggregate'
import type { ExportLocale } from '../shared/types'
import type { AccountInvoiceRow, AccountStatementLabels, AccountStatementTemplateData } from './types'

const sampleParty = {
  id: 'CUS-PREVIEW',
  type: 'customer' as const,
  nameAr: 'محل الأناقة — معاينة',
  nameEn: 'Al-Anaqa Store — Preview',
  phone: '0933 111 222',
  cityAr: 'دمشق',
  cityEn: 'Damascus',
  addressAr: 'المزة — شارع الجلاء',
  addressEn: 'Al-Mazzah — Al-Jalaa St.',
  balance: 128400,
  currency: 'usd' as const,
  creditLimit: 150000,
  status: 'active' as const,
  lastActivity: '2026-06-17',
  invoiceCount: 10,
}

const sampleInvoiceRows: AccountInvoiceRow[] = [
  {
    invoiceNo: 'SINV-1026',
    date: '2026-06-02',
    goodsSummaryAr: 'كتان F12 — أبيض',
    goodsSummaryEn: 'Linen F12 — White',
    pieces: 8,
    totalLength: 3360,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 12.5,
    invoiceTotal: 42000,
    notesAr: 'بيع آجل',
    notesEn: 'Credit sale',
    lineCount: 1,
  },
  {
    invoiceNo: 'SINV-1028',
    date: '2026-06-04',
    goodsSummaryAr: 'قطن مصري — أبيض + بيج',
    goodsSummaryEn: 'Egyptian cotton — White + Beige',
    pieces: 12,
    totalLength: 4820,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 11.2,
    invoiceTotal: 53984,
    notesAr: 'طلبية مختلطة',
    notesEn: 'Mixed order',
    lineCount: 2,
  },
  {
    invoiceNo: 'SINV-1030',
    date: '2026-06-05',
    goodsSummaryAr: 'شيفون — وردي',
    goodsSummaryEn: 'Chiffon — Pink',
    pieces: 5,
    totalLength: 1850,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 9.5,
    invoiceTotal: 17575,
    notesAr: 'تسليم سريع',
    notesEn: 'Express delivery',
    lineCount: 1,
  },
  {
    invoiceNo: 'SINV-1032',
    date: '2026-06-07',
    goodsSummaryAr: 'حرير طبيعي — ذهبي',
    goodsSummaryEn: 'Natural silk — Gold',
    pieces: 3,
    totalLength: 870,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 28,
    invoiceTotal: 24360,
    notesAr: 'صنف خاص',
    notesEn: 'Special item',
    lineCount: 1,
  },
  {
    invoiceNo: 'SINV-1035',
    date: '2026-06-10',
    goodsSummaryAr: 'كتان F12 — أبيض + بيج',
    goodsSummaryEn: 'Linen F12 — White + Beige',
    pieces: 14,
    totalLength: 5880,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 12.5,
    invoiceTotal: 73500,
    notesAr: 'تفنيد من المستودع',
    notesEn: 'Warehouse detailing',
    lineCount: 2,
  },
  {
    invoiceNo: 'SINV-1037',
    date: '2026-06-11',
    goodsSummaryAr: '4 أصناف',
    goodsSummaryEn: '4 items',
    pieces: 18,
    totalLength: 6240,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 10.8,
    invoiceTotal: 67392,
    notesAr: 'فاتورة مجمّعة',
    notesEn: 'Grouped invoice',
    lineCount: 4,
  },
  {
    invoiceNo: 'SINV-1039',
    date: '2026-06-12',
    goodsSummaryAr: 'فيسكوز — أسود',
    goodsSummaryEn: 'Viscose — Black',
    pieces: 6,
    totalLength: 2100,
    unitAr: 'متر',
    unitEn: 'meter',
    avgUnitPrice: 7.5,
    invoiceTotal: 15750,
    notesAr: 'بيع بالمتر',
    notesEn: 'Sold by meter',
    lineCount: 1,
  },
  {
    invoiceNo: 'SINV-1041',
    date: '2026-06-14',
    goodsSummaryAr: 'شيفون S08 — وردي',
    goodsSummaryEn: 'Chiffon S08 — Pink',
    pieces: 6,
    totalLength: 2400,
    unitAr: 'متر',
    unitEn: 'meter',
    avgUnitPrice: 8,
    invoiceTotal: 19200,
    notesAr: 'طلب عاجل',
    notesEn: 'Urgent order',
    lineCount: 1,
  },
  {
    invoiceNo: 'SINV-1043',
    date: '2026-06-15',
    goodsSummaryAr: 'كتان F12 — كحلي',
    goodsSummaryEn: 'Linen F12 — Navy',
    pieces: 9,
    totalLength: 3780,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 13,
    invoiceTotal: 49140,
    notesAr: 'لون جديد',
    notesEn: 'New color',
    lineCount: 1,
  },
  {
    invoiceNo: 'SINV-1045',
    date: '2026-06-17',
    goodsSummaryAr: 'قطن مصري — أبيض',
    goodsSummaryEn: 'Egyptian cotton — White',
    pieces: 7,
    totalLength: 2940,
    unitAr: 'يارد',
    unitEn: 'yard',
    avgUnitPrice: 11,
    invoiceTotal: 32340,
    notesAr: 'آخر فاتورة بالفترة',
    notesEn: 'Last invoice in period',
    lineCount: 1,
  },
]

const sampleVouchers = [
  {
    id: 'AV-1',
    partyId: 'CUS-PREVIEW',
    type: 'receipt' as const,
    ref: 'RCV-220',
    date: '2026-06-08',
    amount: 45000,
    invoiceNo: 'SINV-1026',
    noteAr: 'تحصيل نقدي — دفعة أولى',
    noteEn: 'Cash collection — first payment',
  },
  {
    id: 'AV-2',
    partyId: 'CUS-PREVIEW',
    type: 'receipt' as const,
    ref: 'RCV-228',
    date: '2026-06-14',
    amount: 32000,
    invoiceNo: 'SINV-1035',
    noteAr: 'سند قبض — تحصيل آجل',
    noteEn: 'Receipt voucher',
  },
  {
    id: 'AV-3',
    partyId: 'CUS-PREVIEW',
    type: 'payment' as const,
    ref: 'RET-045',
    date: '2026-06-16',
    amount: 8500,
    invoiceNo: 'SINV-1041',
    noteAr: 'SINV-1041',
    noteEn: 'SINV-1041',
  },
]

export function getAccountStatementSampleData(
  locale: ExportLocale,
  labels: AccountStatementLabels,
): AccountStatementTemplateData {
  const rowTotals = sumAccountInvoiceRows(sampleInvoiceRows)
  const financial = buildAccountFinancialSummary(sampleParty, sampleVouchers, rowTotals.amount)

  return {
    party: sampleParty,
    partyName: locale === 'ar' ? sampleParty.nameAr : sampleParty.nameEn,
    dateFrom: '2026-06-01',
    dateTo: '2026-06-17',
    locale,
    invoiceRows: sampleInvoiceRows,
    vouchers: sampleVouchers,
    financial,
    rowTotals,
    labels,
    reconcile: { date: '2026-06-11', invoiceNo: 'SINV-1037' },
    isSample: true,
  }
}
